#!/bin/bash
# shellcheck disable=SC1090
# SC1090 -- ShellCheck can't follow non-const... that's unfortunate

set -a
shopt -s expand_aliases

BASHIN=1
BASHIN_PATH="${BASH_SOURCE[0]%bashin}"

[[ -e /dev/null ]]&& NULL='/dev/null'

# source libraries (scripts)
import(){
  local lib proc

  for _; do
    [[ $_ =~ / ]]&&{ lib="${_%/*}" proc="${_#*/}"; }|| proc="$_"
    . "${BASHIN_PATH:-./}"lib/"${lib-}"*/"${proc%.sh}.sh"
  done
}

# source all libraries
import_all(){ import std/* sys/*; }

# importing the core libs
import core/{args,loops,stacks}

# defining more practical command names
alias lc=line_count