#!/bin/bash
# shellcheck disable=SC1090
# SC1090 -- ShellCheck can't follow non-const... that's unfortunate

set -aeEuo pipefail
shopt -s expand_aliases

unset path
# set absolute directory
path="${BASH_SOURCE[0]%bashin}"

# source libraries (scripts)
import(){
  unset lib proc
  for _; do
    [[ $_ =~ / ]]&&{ lib="${_%/*}" proc="${_#*/}"; }|| proc="$_"

    . "${path:-.}"/lib/"${lib-}"*/"${proc%.sh}.sh"
  done
}

# source all libraries
import_all(){
  for _ in "${path:-.}"/lib/{sys,std}/*.sh; do
    . "$_"
  done
}

# importing the core libs
import core/{loops,math}

# defining more practical command names
alias lc=line_count
